---
title: ""
author: "Seb Dalgarno"
date: '2018-10-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Seb Dalgarno
#### Masset, BC  
#### seb.dalgarno@gmail.com - 250-626-8978  

I am an ecologist with 4 years of R programming experience. My key skills include: R package development; shiny web app development; statistical modelling; SQLite database creation/ querying; data visualization; spatial data management/manipulation. I also have experience with JavaScript (leaflet.js, d3.js) HTML and CSS for web-based interactive data visualization. Finally, I have published work in scientific journals and have extensive experience managing and conducting remote ecological fieldwork.

### EDUCATION
##### MSc, Geography
###### University of Guelph - Guelph, ON 
###### September 2014 to May 2016
Predictive modeling of Black Oystercatcher distribution in Haida Gwaii, BC  
\  

##### BA, Forest Conservation
###### University of Toronto - Toronto, ON 
###### September 2006 to May 2011  
\  

### WORK EXPERIENCE
##### Computational Biologist
###### Poisson Consulting Ltd. - Masset, BC  
###### January 2017 to Present  
Statistical modeling (Maximum Likelihood, Bayesian); R package development/maintenance; SQLite database creation/management; Shiny app development; spatial data management/manipulation in R; data visualization/map creation in R.  
\  

##### Self-employed Consultant
###### Masset, BC  
###### September 2016 to January 2017  
Various tasks in R: statistical modelling; GIS and spatial analysis; data cleaning and SQLite database creation/management; data visualization; report creation. Contracts with Parks Canada, Habitat Conservation Trust Foundation, Ministry of Forests, Lands and Natural Resource Operations, and Gowgaia Institute.  
\  

##### Researcher
###### University of Geulph - Guelph, ON
###### September 2015 to September 2016
Species Distribution Modelling; shorebird and coastal/intertidal ecology; designed and conducted field work in remote Gwaii Haanas National Park Reserve over 3 weeks by kayak; all analyses/ data management done in R; results published in Avian Conservation Ecology journal.  
\  

##### Teaching Assistant (TA)
###### University of Guelph - Guelph, ON -
###### September 2014 to September 2016
Prepared and delivered presentations; supervised labs; graded assignments; topics covered by courses included statistical analysis, GIS and spatial analysis, remote sensing.  
\  

##### Researcher
###### Canadian Wildlife Service - Queen Charlotte, BC
###### May 2014 to May 2015
Lived and worked in remote part of K'uuna Gwaay Heritage Site/Conservancy retrieving ankle- band GPS loggers from breeding seabirds.  
\  

##### Research Intern
###### Wildlife Conservation Society - Lorengau, Manus, Papua New Guinea
###### September 2012 to September 2014
Designed several scientific studies and managed/conducted field work in remote parts of Papua New Guinean forest; conducted statistical analyses, GIS; results published in Pacific Conservation 
Biology journal.  
\  

##### Research Assistant
###### University of Toronto - Toronto, ON
###### September 2011 to September 2012
Assisted Professor Neera Singh; conducted research on decentralized forest governance, community forestry, and carbon emission reduction projects from deforestation (REDD); prepared manuscripts for publication.  
\  

### SKILLS
`d3.js`, `leaflet.js`, `HTML`, `CSS`, `QGIS`, `ArcGIS`, `SQLite`, `Shiny`, `Machine Learning`, `Generalized Linear Model`, `R`, `Git`, `GitHub`, `Rstudio`, `ggplot2`, `tidyverse`  
\  

### CERTIFICATIONS/LICENCES
PADI Open Water Diver  
Swiftwater Safety Rescue Technician Level 3  
Occupational First Aid

